<?php

function wheniwork_menu() {
	$items = array();

	$items['wiw/schedule'] = array(
		'title' => t('Shift management'),
		'page callback' => 'wheniwork_schedule',
		'access callback' => 'wheniwork_access',
	);

	return $items;
}

function wheniwork_schedule() {
	global $user;

    $user = user_load($user->uid);
var_dump($user);
	return array(
		'#markup' => t('
			<a href="https://api.crisistextline.org/scheduling/login?email=@email&token=@token&fn=@first&ln=@last" class="btn btn-primary btn-lg">Schedule a shift</a>
			<a href="https://api.crisistextline.org/scheduling/login?email=@email&token=@token&fn=@first&ln=@last" class="btn btn-primary btn-lg">View my schedule</a>
			<a href="https://api.crisistextline.org/scheduling/login?email=@email&token=@token&fn=@first&ln=@last" class="btn btn-primary btn-lg">Take time off</a>
			<a href="https://api.crisistextline.org/scheduling/cancel-shift?email=@email&token=@token" class="btn btn-primary btn-lg">Permanently swap shifts</a>', array(
			'@email' => $user->mail,
			'@token' => wheniwork_generate_token($user->mail),
            '@first' => $user->field_first_name[LANGUAGE_NONE][0]['value'],
            '@last' => $user->field_last_name[LANGUAGE_NONE][0]['value'],
		)),
	);
}

function wheniwork_generate_token($email) {
	$token = $email . variable_get('wheniwork_token', 'bananas');

	return sha1($token);
}

function wheniwork_access() {
    global $user;

    $roles = array('Trainer', 'Beta', 'administrator', 'Staff');

    return count(array_intersect($roles, $user->roles));
}
