<?php

define('WHENIWORK_API_URL', 'https://api.crisistextline.org/scheduling');

function wheniwork_menu() {
	$items = array();

	$items['wiw/schedule'] = array(
		'title' => t('Shift management'),
		'page callback' => 'wheniwork_schedule',
		'access callback' => 'user_is_logged_in',
	);

	return $items;
}

function wheniwork_schedule() {
	global $user;

    $user = user_load($user->uid);

	return array(
		'#markup' => t('
			<a href="@API/login?email=@email&token=@token&fn=@first&ln=@last" class="btn btn-primary btn-lg">Schedule a shift</a>
			<a href="@API/login?email=@email&token=@token&fn=@first&ln=@last" class="btn btn-primary btn-lg">View my schedule</a>
			<a href="@API/login?email=@email&token=@token&fn=@first&ln=@last" class="btn btn-primary btn-lg">Take time off</a>
			<a href="@API/cancel-shift?email=@email&token=@token" class="btn btn-primary btn-lg">Permanently swap shifts</a>', array(
			'@email' => urlencode($user->mail),
			'@token' => wheniwork_generate_token($user->mail),
            '@first' => urlencode($user->field_first_name[LANGUAGE_NONE][0]['value']),
            '@last' => urlencode($user->field_last_name[LANGUAGE_NONE][0]['value']),
            '@API' => WHENIWORK_API_URL,
		)),
	);
}

function wheniwork_generate_token($email) {
	$token = $email . variable_get('wheniwork_token', 'bananas');

	return sha1($token);
}
