<?php

/**
 * Implements hook_node_access().
 */
function ctl_features_node_access($node, $op, $account) {
    if (is_object($node) && $node->type == 'application') {
        if ($node->status == 1) {
            if ($op != 'create') {
                return NODE_ACCESS_DENY;
            }
        }
    }
}

/**
 * Implements hook_form_alter().
 */
function ctl_features_form_alter(&$form, &$form_state, $form_id) {
    if ($form_id == 'application_node_form') {
        $form['actions']['draft'] = array(
            '#type' => 'submit',
            '#value' => t('Save as Draft'),
            '#weight' => '9',
            '#submit' => array('_ctl_features_save_draft_submit'),
            '#validate' => array('_ctl_features_save_draft_validate'),
            '#attributes' => array(
                'class' => array('cancel'), // add the class cancel will skip any clientside validation
            ),
        );

        $form['actions']['submit']['#value'] = 'Submit Application';
        $form['actions']['submit']['#validate'][] = '_ctl_features_submit_app';
    }
}

/**
 * Implements hook_for_validate().
 */
function ctl_features_application_node_form_validate($node, $form, &$form_state) {

}

function _ctl_features_save_draft_validate($form, &$form_state) {
    // Force unpublished
    $form_state['values']['status'] = 0;
    $errors = &drupal_static('form_set_error', NULL, TRUE);
}

function _ctl_features_save_draft_submit($form, &$form_state) {
    drupal_get_messages();
    node_form_submit($form, $form_state);
}

function _ctl_features_submit_app($form, &$form_state) {
    global $user;

    $r1email = trim($form_state['values']['field_r1_email_address'][LANGUAGE_NONE][0]['email']);
    $r2email = trim($form_state['values']['field_r2_email_address'][LANGUAGE_NONE][0]['email']);

    if ($r1email == $user->mail || $r2email == $user->mail) {
        form_set_error(
            'r1_email_address',
            t('You cannot enter your own email address as a reference.')
        );
    }

    $form_state['values']['status'] = 1;
}
