<?php

module_load_include('inc', 'schedule_recurring', 'field');

module_load_include('inc', 'schedule_recurring', 'time_off');
module_load_include('inc', 'schedule_recurring', 'make_up');

/**
 * Implements hook_permission().
 */
function schedule_recurring_permission() {
  return array(
    // SHIFTS
    'administer schedule recurring settings' => array(
      'title' => t('Administer schedule recurring'),
      'description' => t('Manage settings for recurring scheduling'),
    ),
    'sign up for shifts' => array(
      'title' => t('Sign up for shifts'),
      'description' => t('Sign up for shifts using schedule recurring'),
    ),
  );
}

/**
 * Implements hook_entity_info().
 */
function schedule_recurring_entity_info() {
  $entities = array(
    'time_off' => schedule_recurring_time_off_entity(),
    'make_up'  => schedule_recurring_make_up_entity(),
  );
  return $entities;
}

/**
 * Implements hook_entity_property_info().
 */
function schedule_recurring_entity_property_info() {
  $info = array(
    'time_off' => array(
      'properties' => array(
        'id' => array(
          'label'        => t('ID'),
          'description'  => t('The ID of the time off entity.'),
          'type'         => 'integer',
          'schema field' => 'id',
        ),
        'author' => array(
          'label'        => t('Author'),
          'description'  => t('The ID of who is requesting time off.'),
          'type'         => 'integer',
          'schema field' => 'author',
        ),
        'start' => array(
          'label'        => t('Start date'),
          'description'  => t('The start date of the time off.'),
          'type'         => 'date',
          'schema field' => 'start',
        ),
        'end' => array(
          'label'        => t('End date'),
          'description'  => t('The end date of the time off.'),
          'type'         => 'date',
          'schema field' => 'end',
        ),
        'reason' => array(
          'label'        => t('Reason'),
          'description'  => t('Reason for taking time off.'),
          'type'         => 'text',
          'schema field' => 'reason',
        ),
        'type' => array(
          'label'        => t('Time off type'),
          'description'  => t('The type of time off (which is named after a user role).'),
          'type'         => 'text',
          'schema field' => 'type',
        ),
      ),
    ),
  );
  return $info;
}

/**
 * Implements hook_entity_property_info_alter().
 */
function schedule_recurring_entity_property_info_alter(&$info) {
  $info['time_off']['properties']['id']['type'] = 'user';
  // $info['time_off']['properties']['start']['handler'] = 'date_views_filter_handler';
  // $info['time_off']['properties']['start']['is date'] = TRUE;
}

/**
 * Implements hook_menu().
 */
function schedule_recurring_menu() {
  $items = array();

  $items['admin/config/schedule_recurring'] = array(
    'title' => t('Recurring Scheduler settings'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('schedule_recurring_admin'),
    'access arguments' => array('administer schedule recurring settings'),
    'type' => MENU_NORMAL_ITEM,
  );

  $items['schedule/my-schedule'] = array(
    'title' => t('My Schedule'),
    'file' => 'schedule.inc',
    'file path' => drupal_get_path('module', 'schedule_recurring'),
    'page callback' => 'schedule_recurring_my_schedule',
    'access arguments' => array('sign up for shifts'),
    'type' => MENU_NORMAL_ITEM,
  );

  $items['schedule/sign-up'] = array(
    'title' => t('Shift scheduling'),
    'file' => 'schedule.inc',
    'file path' => drupal_get_path('module', 'schedule_recurring'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('schedule_recurring_available'),
    'access arguments' => array('sign up for shifts'),
    'type' => MENU_NORMAL_ITEM,
  );

  $items['schedule/confirm'] = array(
    'title' => t('Shift confirmation'),
    'file' => 'schedule.inc',
    'file path' => drupal_get_path('module', 'schedule_recurring'),
    'page callback' => 'schedule_recurring_confirm',
    'access arguments' => array('sign up for shifts'),
    'type' => MENU_NORMAL_ITEM,
  );

  $items['schedule'] = array(
    'title' => t('Schedule'),
    'file' => 'schedule.inc',
    'file path' => drupal_get_path('module', 'schedule_recurring'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('schedule_recurring_schedule'),
    'access arguments' => array('sign up for shifts'),
    'type' => MENU_NORMAL_ITEM,
  );

  /**
   * Time off
   */

  $items['time-off'] = array(
    'title' => t('Take time off'),
    'page callback' => 'time_off_add',
    'access arguments' => array('sign up for shifts'),
    'file' => 'time_off.inc',
    'file path' => drupal_get_path('module', 'schedule_recurring'),
  );

  $items['time-off/%'] = array(
    'page callback' => 'time_off_view',
    'page arguments' => array(1),
    'access arguments' => array('sign up for shifts'),
    'file' => 'time_off.inc',
    'file path' => drupal_get_path('module', 'schedule_recurring'),
  );

  $items['time-off/%/edit'] = array(
    'page callback' => 'drupal_get_form',
    'page arguments' => array('time_off_form', 1),
    'access arguments' => array('sign up for shifts'),
    'file' => 'time_off.inc',
    'file path' => drupal_get_path('module', 'schedule_recurring'),
  );

  $items['time-off/%/delete'] = array(
    'page callback' => 'time_off_delete',
    'page arguments' => array(1),
    'access arguments' => array('sign up for shifts'),
    'file' => 'time_off.inc',
    'file path' => drupal_get_path('module', 'schedule_recurring'),
  );

  /**
   * Make ups
   */
  $items['make-up'] = array(
    'title' => t('Make up a shift'),
    'page callback' => 'make_up_add',
    'access arguments' => array('sign up for shifts'),
    'file' => 'make_up.inc',
    'file path' => drupal_get_path('module', 'schedule_recurring'),
  );

  $items['make-up/%'] = array(
    'page callback' => 'make_up_view',
    'page arguments' => array(1),
    'access arguments' => array('sign up for shifts'),
    'file' => 'make_up.inc',
    'file path' => drupal_get_path('module', 'schedule_recurring'),
  );

  $items['make-up/%/cancel'] = array(
    'page callback' => 'make_up_delete',
    'page arguments' => array(1),
    'access arguments' => array('sign up for shifts'),
    'file' => 'make_up.inc',
    'file path' => drupal_get_path('module', 'schedule_recurring'),
  );

  return $items;
}

/**
 * Menu callback for module settings.
 */
function schedule_recurring_admin() {
  $form = array();

  $mapping = variable_get('schedule_recurring_shift_mapping', array());
  $mapping[] = array(
    'publisher' => '',
    'subscriber' => '',
    'points' => '',
  );

  $form['schedule_recurring_shift_mapping'] = array(
    '#theme' => 'table',
    '#tree' => TRUE,
    '#suffix' => t('Reset a role to "- Select -" to remove it from the mapping.'),
    '#rows' => array(),
    '#header' => array('Shift publisher', 'Shift subscriber', 'Points'),
  );


  foreach ($mapping as $key => $map) {
    $form['schedule_recurring_shift_mapping'][$key]['publisher'] = array(
      '#type' => 'select',
      '#options' => array('' => '- Select -') + user_roles(),
      '#default_value' => $map['publisher'],
    );

    $form['schedule_recurring_shift_mapping'][$key]['subscriber'] = array(
      '#type' => 'select',
      '#options' => array('' => '- Select -') + user_roles(),
      '#default_value' => $map['subscriber'],
    );

    $form['schedule_recurring_shift_mapping'][$key]['points'] = array(
      '#type' => 'textfield',
      '#default_value' => $map['points'],
      '#size' => 3,
    );

    $form['schedule_recurring_shift_mapping']['#rows'][] = array(
      array(
        'data' => &$form['schedule_recurring_shift_mapping'][$key]['publisher'],
      ), array(
        'data' => &$form['schedule_recurring_shift_mapping'][$key]['subscriber'],
      ), array(
        'data' => &$form['schedule_recurring_shift_mapping'][$key]['points'],
      ),
    );
  }

  $form['schedule_recurring_points_per_block'] = array(
    '#type' => 'textfield',
    '#element_validate' => array('element_validate_number'),
    '#title' => t('Maximum number of points available during a timeslot.'),
    '#default_value' => variable_get('schedule_recurring_points_per_block', 100),
    '#size' => 5,
  );

  $form['schedule_recurring_shift_increment'] = array(
    '#type' => 'textfield',
    '#element_validate' => array('element_validate_number'),
    '#title' => t('Shift interval'),
    '#field_prefix' => 'start a shift every',
    '#field_suffix' => 'minutes',
    '#default_value' => variable_get('schedule_recurring_shift_increment', 30),
    '#size' => 5,
  );

  $form['schedule_recurring_shift_duration'] = array(
    '#type' => 'textfield',
    '#element_validate' => array('element_validate_number'),
    '#title' => t('Shift length'),
    '#field_suffix' => 'minutes',
    '#default_value' => variable_get('schedule_recurring_shift_duration', 240),
    '#size' => 5,
  );

  $form['schedule_recurring_priority_shifts'] = array(
    '#type' => 'textarea',
    '#title' => t('Prioritized shifts'),
    '#rows' => 10,
    '#description' => 'One time range per line. For Monday (0-based day 1 of the week), 3pm-11pm, use: 1:1500-2300',
    '#default_value' => implode("\n", variable_get('schedule_recurring_priority_shifts', array())),
  );

  $form['schedule_recurring_shift_email'] = array(
    '#type' => 'textarea',
    '#title' => t('Shift confirmation email text'),
    '#rows' => 10,
    '#description' => 'The email will start with "Name, Your DURATION shift has been confirmed for DAY starting at TIME.',
    '#default_value' => variable_get('schedule_recurring_shift_email', ''),
  );

  $form = system_settings_form($form);
  array_unshift($form['#submit'], '_schedule_recurring_admin_submit');

  return $form;
}

function schedule_recurring_cron() {

}

function _schedule_recurring_admin_submit($form, &$form_state) {
  $form_state['values']['schedule_recurring_priority_shifts'] = explode("\n", $form_state['values']['schedule_recurring_priority_shifts']);
  foreach ($form_state['values']['schedule_recurring_shift_mapping'] as $key => $map) {
    if (empty($map['publisher']) || empty($map['subscriber'])) {
      unset($form_state['values']['schedule_recurring_shift_mapping'][$key]);
    }
  }
}

function schedule_recurring_is_publisher() {
  global $user;

  $mapping = variable_get('schedule_recurring_shift_mapping');

  foreach ($mapping as $role) {
    if (isset($user->roles[$role['publisher']])) {
      return true;
    }
  }

  return false;
}
/**
 * Internal method for who is a setter.
 */
function _schedule_recurring_setters() {
  $setters = &drupal_static(__FUNCTION__);

  if (!isset($setters)) {
    $setters = variable_get('schedule_recurring_shift_setters', array());
    $setters = array_filter(array_values($setters), function ($var) {
      return $var != 0;
    });
  }

  return $setters;
}


function _schedule_recurring_days($pluralize = TRUE) {
  if ($pluralize) {
    return array(
      'Sundays',
      'Mondays',
      'Tuesdays',
      'Wednesdays',
      'Thursdays',
      'Fridays',
      'Saturdays',
    );
  } else {
    return array(
      'Sunday',
      'Monday',
      'Tuesday',
      'Wednesday',
      'Thursday',
      'Friday',
      'Saturday',
    );
  }
}

function _schedule_recurring_times($include_2400 = FALSE) {
  static $times;

  $accessor = ($include_2400) ? 'include' : 'exclude';
  $interval = variable_get('schedule_recurring_shift_increment');

  if (!isset($times[$accessor])) {
    $times[$accessor] = array();

    for ($i = 0; $i < 24; $i++) {
      for ($j = 0; $j < 60; $j += $interval) {
        $k = $j < 10 ? '0'.$j : $j;
        $times[$accessor][intval($i . $k)] = (($i % 12) ?: 12) . ':'.$k.' '. (($i < 12) ? 'am' : 'pm');
      }
    }

    if ($accessor == 'include') {
      unset($times[$accessor][0]);
      $times[$accessor][2400] = '12:00 am (following day)';
    }
  }

  return $times[$accessor];
}

function schedule_recurring_next_shift($num_increments = 1) {
  $increment = variable_get('schedule_recurring_shift_increment');

  $today = date('w');

  $next_minutes = (floor(date('i') / $increment) * $increment) + ($increment * $num_increments);
  $next_hour = date('H') + floor($next_minutes / 60);

  if ($next_minutes >= 60) {
    $next_minutes = $next_minutes % 60;
  }

  $next_shift = $next_hour . str_pad($next_minutes, 2, '0', STR_PAD_LEFT);

  return $next_shift;
}

function schedule_recurring_mail($key, &$message, $params) {
  switch ($key) {
    case 'shift_confirmation':
      $days  = _schedule_recurring_days();
      $day   = $days[$params['shift']['day']];
      $times = _schedule_recurring_times();
      $start = $times[$params['shift']['start']];
      $name  = format_username($params['account']);

      $message['subject'] = t('Welcome aboard!');

      $raw_message = implode(PHP_EOL, array(
        '<p>Congrats, @name!</p>',
        '',
        "<p>All graduated and signed up for your shift time, that's HUGE!</p>",
        '',
        '<p><strong>Your first shift is @day at @start.</strong></p>',
        '',
        '<p>Here are a few pro tips to help you rock your first shift:</p>',
        '',
        '<ul>',
          "<li>Your supervisor's name is on the upper left corner of your screen (say hello!)</li>",
          '<li>Enter your status under your name (suggestion: "First Shift" - or some funky version of this, so your fellow crisis counselors know to say hello!)</li>',
          '<li>Only take 1 conversation at a time</li>',
          '<li>NEVER feel like you are alone, your peers and supervisors are there to help!</li>',
          '<li>Say hi to everyone in the Global Chat let them know you are new - join the convo (it’s a fun crew!)</li>',
          "<li>If you aren't able to make your first shift, please <a href=\"https://online.crisistextline.org/time-off\">request time off</a> here.",
        '</ul>',
        '',
        '<p>You passed training. You have all of the tools and knowledge you need to be great crisis counselor - you got this!</p>',
        '',
        "<p>Oh! And who the heck am I? I'm Jen James,  Director of Crisis Counselors. I'm your ears and eyes on the platform; if you have questions, suggestions, or concerns you can come to me!</p>",
        '',
        '<p>Cheers,<br />',
        'Jen James<br />',
        'Director of Crisis Counselors<br />',
        'Crisis Text Line</p>',
        '',
        "P.S. I like to jam out during my shifts. Here's a <a href=\"https://play.spotify.com/user/crisistextlinecounselors/playlist/0gXOfDnE8h8G5o7iYaCiN0\">Spotify Playlist for Crisis Counselors</a> - jam out with me!",
      ));

      $message['body'][] = t($raw_message, array(
        '@name'  => $name,
        '@day'   => $day,
        '@start' => $start,
      ));

      break;
  }
}
