<?php

module_load_include('inc', 'schedule_recurring', 'field');

/**
 * Implements hook_permission().
 */
function schedule_recurring_permission() {
  return array(
    'administer schedule recurring settings' => array(
      'title' => t('Administer schedule recurring'),
      'description' => t('Manage settings for recurring scheduling'),
    ),
    'sign up for shifts' => array(
      'title' => t('Sign up for shifts'),
      'description' => t('Sign up for shifts using schedule recurring'),
      ),
  );
}


/**
 * Implements hook_menu().
 */
function schedule_recurring_menu() {
  $items = array();

  $items['admin/config/schedule_recurring'] = array(
    'title' => 'Recurring Scheduler settings',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('schedule_recurring_admin'),
    'access arguments' => array('administer schedule recurring settings'),
    'type' => MENU_NORMAL_ITEM,
  );

  $items['schedule'] = array(
    'title' => 'Shift scheduling',
    'file' => 'schedule.inc',
    'file path' => drupal_get_path('module', 'schedule_recurring'),
    'page callback' => 'schedule_recurring_schedule',
    'access arguments' => array('sign up for shifts'),
    'type' => MENU_NORMAL_ITEM,
  );
  
  return $items;
}

/**
 * Menu callback for module settings.
 */
function schedule_recurring_admin() {
  $form = array();

  $form['schedule_recurring_shift_setters'] = array(
    '#type' => 'checkboxes',
    '#multiple' => TRUE,
    '#options' => user_roles(),
    '#default_value' => variable_get('schedule_recurring_shift_setters', array()),
    '#description' => t('The roles whose shifts will define the available shifts.'),
    '#title' => t('Shift availability definers'),
    '#required' => FALSE,
  );

  $form['schedule_recurring_users_per_block'] = array(
    '#type' => 'textfield',
    '#element_validate' => array('element_validate_number'),
    '#title' => t('Maximum number of users to be supervised during a timeslot.'),
    '#default_value' => variable_get('schedule_recurring_users_per_block', 50),
    '#size' => 5,
  );

  $form['schedule_recurring_shift_increment'] = array(
    '#type' => 'textfield',
    '#element_validate' => array('element_validate_number'),
    '#title' => t('Shift interval'),
    '#field_prefix' => 'start a shift every',
    '#field_suffix' => 'minutes',
    '#default_value' => variable_get('schedule_recurring_shift_increment', 30),
    '#size' => 5,
  );

  $form['schedule_recurring_shift_duration'] = array(
    '#type' => 'textfield',
    '#element_validate' => array('element_validate_number'),
    '#title' => t('Shift length'),
    '#field_suffix' => 'minutes',
    '#default_value' => variable_get('schedule_recurring_shift_duration', 240),
    '#size' => 5,
  );

  return system_settings_form($form);
}

/**
 * Internal method for who is a setter.
 */
function _schedule_recurring_setters() {
  $setters = &drupal_static(__FUNCTION__);

  if (!isset($setters)) {
    $setters = variable_get('schedule_recurring_shift_setters', array());
    $setters = array_filter(array_values($setters), function ($var) {
      return $var != 0;
    });
  }

  return $setters;
}


function _schedule_recurring_days() {
  return array(
    'Sunday',
    'Monday',
    'Tuesday',
    'Wednesday',
    'Thursday',
    'Friday',
    'Saturday',
  );
}

function _schedule_recurring_times($include_2400 = FALSE) {
  static $times;

  $accessor = ($include_2400) ? 'include' : 'exclude';
  $interval = variable_get('schedule_recurring_shift_increment');

  if (!isset($times[$accessor])) {
    $times[$accessor] = array();

    for ($i = 0; $i < 24; $i++) {
      for ($j = 0; $j < 60; $j += $interval) {
        $k = $j < 10 ? '0'.$j : $j;
        $times[$accessor][intval($i . $k)] = (($i % 12) ?: 12) . ':'.$k.' '. (($i < 12) ? 'am' : 'pm');
      }
    }

    if ($accessor == 'include') {
      unset($times[$accessor][0]);
      $times[$accessor][2400] = '12:00 am (following day)';
    }
  }
  
  return $times[$accessor];
}

