; Contrib modules, themes and libraries

api = 2
core = 7.x

defaults[projects][subdir] = "contrib"

; Theme
projects[adminimal_theme][version] = "1.23"

; Libraries
libraries[mandrill][download][type] = "get"
libraries[mandrill][download][url] = "https://bitbucket.org/mailchimp/mandrill-api-php/get/1.0.54.zip"
libraries[mandrill][directory_name] = "mandrill"

libraries[twilio][download][type] = "get"
libraries[twilio][download][url] = "https://github.com/twilio/twilio-php/archive/master.zip"
libraries[twilio][directory_name] = "twilio"

libraries[SimpleSAMLphp][download][type] = "get"
libraries[SimpleSAMLphp][download][url] = "https://simplesamlphp.org/res/downloads/simplesamlphp-1.13.2.tar.gz"
libraries[SimpleSAMLphp][directory_name] = "simplesamlphp"

; Modules
projects[addressfield][version] = "1.2"
projects[admin_menu][version] = "3.0-rc5"
projects[admin_views][version] = "1.5"
projects[auto_nodetitle][version] = "1.0"
projects[better_exposed_filters][version] = "3.2"
projects[cas][version] = "1.x-dev"
projects[computed_field][version] = "1.0"
projects[conditional_fields][version] = "3.0-alpha2"
projects[content_access][version] = "1.2-beta2"
projects[ctools][version] = "1.9"
projects[course][version] = "1.6"
projects[course_relationships][version] = "1.x-dev"
projects[custom_webform_comments][version] = "1.0"
projects[custom_webform_comments][download][type] = "git"
projects[custom_webform_comments][download][url] = "http://git.drupal.org/project/custom_webform_comments.git"
projects[custom_webform_comments][download][revision] = "77ac3b1a1c12cf044e8118800e2fd978e807c041"
projects[custom_webform_comments][patch][] = https://www.drupal.org/files/issues/custom_webform_comments-timestamp-format-2527778-1.patch
projects[date][version] = "2.9"
# projects[devel][version] = "1.x-dev"
projects[drupalchat][version] = "1.7"
projects[drupalchat][patch][] = https://www.drupal.org/files/issues/drupalchat-format-username-2507175-4.patch
projects[editablefields][version] = "1.x-dev"
projects[email][version] = "1.3"
projects[email_registration][version] = "1.3"
projects[entity][version] = "1.6"
projects[entityreference][version] = "1.1"
projects[entityreference_prepopulate][version] = "1.5"
projects[features][version] = "2.7"
projects[field_formatter_class][version] = "1.1"
projects[field_formatter_settings][version] = "1.1"
projects[field_group][version] = "1.5"
projects[field_group_ajaxified_multipage][version] = "1.1"
projects[field_permissions][version] = "1.0-beta2"
projects[filefield_nginx_progress][version] = "2.3"
projects[inline_registration][version] = "1.0"
projects[libraries][version] = "2.2"
projects[mailcontrol][version] = "1.0"
projects[mailsystem][version] = "2.34"
projects[mandrill][version] = "2.2"
projects[module_filter][version] = "2.0"
projects[multipage_jumplist][version] = "1.0-alpha1"
# projects[multiple_fields_remove_button][version] = "1.4"
# projects[nodejs][version] = "1.x-dev"
projects[node_clone][version] = "1.0"
projects[node_limit][version] = "1.0-alpha5"
projects[no_trimmed_preview][version] = "1.0"
# projects[orchid][version] = "2.x-dev"
# projects[orchid][patch][] = https://www.drupal.org/files/issues/orchid-format_username-1869682-1-7.x.patch
# projects[og][version] = "2.7"
projects[privatemsg][version] = "1.4"
projects[quiz][version] = "5.0-beta1"
projects[realname][version] = "1.2"
projects[redirect][version] = "1.0-rc3"
projects[required_by_role][version] = "1.7"
projects[rules][version] = "2.9"
projects[rules][patch][] = https://www.drupal.org/files/rules-site-property-metadata-fix-1423234-15.patch
projects[services][version] = "3.x-dev"
projects[services_api_key_auth][version] = "1.0"
projects[services_entity][version] = "2.0-alpha8"
projects[services_rules][version] = "1.0-beta1"
projects[simplesamlphp_auth][version] = "2.x-dev"
projects[rules_conditional][version] = "1.0-beta2"
projects[token][version] = "1.6"
projects[twilio][version] = "1.11"
projects[uuid][version] = "1.0-beta1"
projects[video][version] = "2.11"
projects[views][version] = "3.11"
projects[views_bulk_operations][version] = "3.3"
projects[views_field_view][version] = "1.2"
projects[views_fieldsets][version] = "1.3"
projects[views_data_export][version] = "3.0-beta9"
projects[views_role_based_global_text][version] = "1.1"
projects[views_date_format_sql][version] = "3.1"
projects[webform][version] = "4.12"
projects[webform_references][version] = "1.8"
projects[webform_validation][version] = "1.10"

# ; Forums
# projects[advanced_forum][version] = "2.6"
# projects[advanced_forum_bootstrap][version] = "3.x-dev"
# projects[forum_access][version] = "1.2"
# projects[chain_menu_access][version] = "2.0"
# projects[acl][version] = "1.1"

# DrupalAuth
#projects[drupalauth][type] = "module"
#projects[drupalauth][subdir] = "ctl"
#projects[drupalauth][download][type] = "get"
#projects[drupalauth][download][source] = "https://storage.googleapis.com/google-code-archive-downloads/v2/code.google.com/drupalauth/drupalauth-1.2.2_1.x_7.x.tar.gz"
