<?php

define('CTL_ONBOARDING_REGISTRATION_CLOSED', 0);
define('CTL_ONBOARDING_REGISTRATION_OPEN', 1);

define('CTL_ONBOARDING_STATUS_PENDING', 0);
define('CTL_ONBOARDING_STATUS_ACCEPTED', 1);
define('CTL_ONBOARDING_STATUS_WAIT_LISTED', 2);
define('CTL_ONBOARDING_STATUS_DROPPED_FAILED_BACKGROUND_CHECK', 3);
define('CTL_ONBOARDING_STATUS_DROPPED_CANCELED_BY_REGISTRANT', 4);
define('CTL_ONBOARDING_STATUS_DROPPED_OTHER', 5);

define('CTL_ONBOARDING_DEFAULT_TRAINER_CAPACITY', 35);

// Hours are defined in 24-hour clock time (a.k.a. military time).
define('CTL_ONBOARDING_FIRST_START_HOUR', 800);
define('CTL_ONBOARDING_LAST_START_HOUR', 1900);
define('CTL_ONBOARDING_ONE_HOUR', 100);
define('CTL_ONBOARDING_SESSION_DURATION', 1900);

require_once DRUPAL_ROOT . '/' . drupal_get_path('module', 'ctl_onboarding') . '/includes/helper.inc';


/**
 * Implements hook_menu().
 */
function ctl_onboarding_menu() {
  $items['registration'] = array(
    'title'            => 'Training Session Registration',
    'page callback'    => 'drupal_get_form',
    'page arguments'   => array('ctl_onboarding_form'),
    'access arguments' => array('register for training'),
    'type'             => MENU_CALLBACK,
    'file'             => 'includes/registration.inc',
  );
  $items['admin/config/ctl'] = array(
    'title'            => 'Crisis Text Line',
    'description'      => 'Configure CTL settings.',
    'position'         => 'right',
    'weight'           => -100,
    'page callback'    => 'system_admin_menu_block_page',
    'access arguments' => array('administer site configuration'),
    'file'             => 'system.admin.inc',
    'file path'        => drupal_get_path('module', 'system'),
  );
  $items['admin/config/ctl/ctl-onboarding'] = array(
    'title'            => 'CTL Onboarding',
    'page callback'    => 'drupal_get_form',
    'page arguments'   => array('_ctl_onboarding_settings_form'),
    'access arguments' => array('administer onboarding'),
    'type'             => MENU_NORMAL_ITEM,
    'file'             => 'includes/admin.inc',
  );
  return $items;
}


/**
 * Implements hook_permission().
 */
function ctl_onboarding_permission() {
  return array(
    'administer onboarding' => array(
      'title'       => t('Administer onboarding'),
      'description' => t('Manage cohort training session registration.'),
    ),
    'register for training' => array(
      'title'       => t('Register for training'),
      'description' => t('Allow users to sign up for a training session.'),
    ),
  );
}


/**
 * Implements hook_theme().
 */
function ctl_onboarding_theme($existing, $type, $theme, $path) {
  return array(
    'ctl_onboarding_table' => array(
      'render element' => 'element',
      'file'           => 'includes/theme.inc',
    ),
  );
}
