<?php
/**
 * @file
 * Code for the CTL Office Hours feature.
 */

include_once 'ctl_office_hours.features.inc';

/**
 * Implements hook_views_pre_render().
 */
function ctl_office_hours_views_pre_render(&$view) {
  global $user;

  if ($view->name == 'office_hours') {
    if (in_array('Trainee', $user->roles)) {
      unset($view->field['join_moderator']);
    } else {
      unset($view->field['join_attendee']);
    }
  }
}