<?php

/**
 * Implements hook_menu().
 */
function ctl_graduation_button_menu() {
  $items = array();

  $items['user/%user/certificate'] = array(
    'title'            => 'Certificate',
    'page callback'    => '_ctl_graduation_button_certificate_page',
    'page arguments'   => array(1),


    // user_is_logged_in

    'access callback'  => TRUE,
    // 'access arguments' => array('access content'),

    'type'             => MENU_CALLBACK,
    'file' => 'includes/certificate.inc',
  );

  $items['user/%user/progress'] = array(
    'title'           => 'Progress',
    'page callback'   => '_ctl_graduation_button_progress_page',
    'page arguments'  => array(1),

    'access callback' => TRUE,
    // 'access arguments' => array('access content'),

    'type'            => MENU_LOCAL_TASK,
    'file' => 'includes/progress.inc',
  );

  return $items;
}
