<?php

/**
 * Implements hook_menu().
 */
function ctl_graduation_button_menu() {
  $items['user/%user/progress'] = array(
    'title'            => 'Progress',
    'page callback'    => '_ctl_graduation_button_progress_page',
    'page arguments'   => array(1),
    'access arguments' => array('access all course reports'),
    'type'             => MENU_LOCAL_TASK,
    'file'             => 'includes/progress.inc',
  );
  return $items;
}
