<?php

/**
 * Implements hook_menu().
 */
function ctl_canvas_menu() {

  $items = array(
    'training' => array(
      'title'            => 'Training',
      'page callback'    => '_ctl_canvas_training_page',
      'access callback'  => '_ctl_canvas_training_access',
      'type'             => MENU_LOCAL_TASK,
    ),
  );

  return $items;
}


function _ctl_canvas_training_page() {
  global $user;

  $account = user_load($user->uid);

  if (isset($account->field_canvas) && $account->field_canvas[LANGUAGE_NONE][0]['value'] == 1) {
    drupal_goto('https://crisistextline.instructure.com/');
  } else {
    drupal_goto('training-archives');
  }
}

function _ctl_canvas_training_access() {
  global $user;

  $access = array(
    'Trainee',
    'Staff',
    'Trainer',
    'administrator',
    'Graduate'
  );

  $collision = array_intersect(array_values($user->roles), $access);

  return count($collision > 0);
}

/**
 * Implements hook_user_presave().
 */
function ctl_canvas_user_presave(&$edit, $account, $category) {
  // Makes sure that the username is the user's email in order for
  // SSO integration between Drupal and Canvas to work correctly.
  if (isset($edit['mail'])) {
    $edit['name'] = $edit['mail'];
  } else {
    $edit['name'] = $account->mail;
  }
}
