<?php

function _ctl_onboarding_registration_test() {

  // // http://knackforge.com/blog/vishnu/programmatically-create-node-drupal-7

  // $complaint_body = 'Your node complaint body text';

  // $node = new stdClass();
  // $node->type = 'training_team';
  // $node->language = LANGUAGE_NONE;
  // node_object_prepare($node);

  // $node->title = 'Your node title';

  // $node->body[$node->language][0]['value']   = $complaint_body;
  // $node->body[$node->language][0]['summary'] = text_summary($complaint_body);
  // $node->body[$node->language][0]['format']  = 'full_html';

  // $node->status  = NODE_PUBLISHED;
  // $node->promote = NODE_NOT_PROMOTED;
  // $node->sticky  = NODE_NOT_STICKY;
  // $node->comment = COMMENT_NODE_HIDDEN;

  // // Add author of the node
  // $node->uid = 1;

  // // Set created date
  // $node->date    = 'complaint_post_date';
  // $node->created = strtotime('complaint_post_date');

  // $path       = 'content/mytest-' . date('YmdHis');
  // $node->path = array('alias' => $path);

  // node_save($node);



  // $node = node_load(2);

  // $user = user_load(3);

  // // http://zbozien.co.uk/blog/2015/02/28/drupal-add-user-to-og-group-and-delete-from-group-membership/

  // // Add the user to the group.
  // og_group('node', $node->nid, array(
  //   'entity type'     => 'user',
  //   'entity'          => $user,
  //   'membership type' => OG_MEMBERSHIP_TYPE_DEFAULT,
  // ));





  return 'hi';
}
