<?php

/**
 * Implements hook_menu().
 */
function ctl_graduation_menu() {
  $items['user/%user/certificate'] = array(
    'title'            => 'Certificate',
    'description'      => 'The CTL certificate for graduates.',
    'page callback'    => '_ctl_graduation_certificate_page',
    'page arguments'   => array(1),
    'access arguments' => array('view certificate'),
    'type'             => MENU_CALLBACK,
    'file'             => 'includes/certificate.inc',
  );
  $items['user/%user/progress'] = array(
    'title'            => 'Progress',
    'page callback'    => '_ctl_graduation_progress_page',
    'page arguments'   => array(1),
    'access arguments' => array('access all course reports'),
    'type'             => MENU_LOCAL_TASK,
    'file'             => 'includes/progress.inc',
  );
  return $items;
}


/**
 * Implements hook_permission().
 */
function ctl_graduation_permission() {
  return array(
    'view certificate' => array(
      'title' => t('View certificate'),
      'description' => t('View the graduation certificate'),
    ),
    'view graduates' => array(
      'title' => t('View graduates'),
      'description' => t('View the list of graduates'),
    ),
  );
}


/**
 * Implements hook_theme().
 */
function ctl_graduation_theme($existing, $type, $theme, $path) {
  if ($type === 'module') {
    $themes['page__certificate'] = array(
      'template' => 'templates/page--certificate',
      'variables' => array(
        'certificate_image' => NULL,
        'graduate_name'     => NULL,
        'graduation_date'   => NULL,
      ),
    );
    $themes['graduation_message'] = array(
      'template' => 'templates/graduation_message',
      'variables' => array(
        'graduate_name' => NULL,
        'graduate_uid'  => NULL,
        'trainer_name'  => NULL,
      ),
    );
  }
  return $themes;
}
